# Generated by Django 5.2.13 on 2026-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('segment', models.CharField(blank=True, max_length=120)),
                ('current_stage', models.CharField(choices=[('problem', 'Definicao do problema'), ('audience', 'Publico-alvo'), ('value', 'Proposta de valor'), ('validation', 'Validacao inicial'), ('mvp', 'Planejamento do MVP')], default='problem', max_length=20)),
                ('initial_goal', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'ordering': ['name'],
            },
        ),
    ]
