# Generated by Django 5.2.13 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0002_startup_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="audience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="startup",
            name="problem",
            field=models.TextField(blank=True),
        ),
    ]
