# Generated by Django 5.2.16 on 2026-07-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_audience_startup_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='current_stage',
            field=models.CharField(choices=[('problem', 'Definicao do problema'), ('audience', 'Publico-alvo'), ('value', 'Proposta de valor'), ('differentiators', 'Diferenciais'), ('validation', 'Validacao inicial'), ('business_model', 'Modelo de negocio'), ('mvp', 'Planejamento do MVP'), ('goals', 'Metas iniciais')], default='problem', max_length=20),
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('problem', 'Definicao do problema'), ('audience', 'Publico-alvo'), ('value', 'Proposta de valor'), ('differentiators', 'Diferenciais'), ('validation', 'Validacao inicial'), ('business_model', 'Modelo de negocio'), ('mvp', 'Planejamento do MVP'), ('goals', 'Metas iniciais')], max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('current', 'Etapa atual'), ('done', 'Concluida')], default='pending', max_length=10)),
                ('order', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Etapa da jornada',
                'verbose_name_plural': 'Etapas da jornada',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('startup', 'key'), name='unique_step_per_startup')],
            },
        ),
    ]
