# Generated by Django 5.2.16 on 2026-07-13 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_startup_current_stage_journeystep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('mission_type', models.CharField(choices=[('main', 'Missao principal'), ('weekly', 'Missao semanal'), ('quick', 'Tarefa rapida'), ('experiment', 'Experimento'), ('learning', 'Aprendizado'), ('management', 'Gestao recorrente')], default='main', max_length=20)),
                ('phase', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('objective', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('instructions', models.JSONField(default=list)),
                ('completion_criteria', models.TextField()),
                ('contextual_tip', models.TextField(blank=True)),
                ('required_evidence_count', models.PositiveSmallIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Bloqueada'), ('available', 'Disponivel'), ('in_progress', 'Em andamento'), ('completed', 'Concluida')], default='locked', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Missao',
                'verbose_name_plural': 'Missoes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('impact', models.TextField()),
                ('next_action', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='startups.startup')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnings', to='startups.mission')),
            ],
            options={
                'verbose_name': 'Aprendizado',
                'verbose_name_plural': 'Aprendizados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('interview', 'Entrevista'), ('experiment', 'Resultado de experimento'), ('document', 'Documento'), ('metric', 'Metrica'), ('other', 'Outra evidencia')], default='interview', max_length=20)),
                ('interviewee_name', models.CharField(max_length=120)),
                ('interviewee_profile', models.CharField(blank=True, max_length=180)),
                ('context', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField()),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='startups.mission')),
            ],
            options={
                'verbose_name': 'Evidencia de missao',
                'verbose_name_plural': 'Evidencias de missao',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('interview_recorded', 'Entrevista registrada'), ('learning_recorded', 'Aprendizado registrado'), ('mission_completed', 'Missao concluida'), ('journey_step_completed', 'Etapa concluida'), ('decision_recorded', 'Decisao registrada'), ('goal_completed', 'Meta concluida')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('dedupe_key', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Atividade significativa',
                'verbose_name_plural': 'Atividades significativas',
                'ordering': ['-occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('startup', 'dedupe_key'), name='unique_activity_event_per_startup')],
            },
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('startup', 'key'), name='unique_mission_per_startup'),
        ),
        migrations.AddConstraint(
            model_name='learning',
            constraint=models.UniqueConstraint(fields=('startup', 'mission'), name='unique_learning_per_mission'),
        ),
    ]
