# Generated by Django 5.2.16 on 2026-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startup_last_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='action_type',
            field=models.CharField(choices=[('interviews', 'Entrevistas'), ('problem_refinement', 'Refinamento do problema'), ('audience_validation', 'Validacao do publico'), ('value_proposition', 'Proposta de valor'), ('alternatives_map', 'Mapa de alternativas')], default='interviews', max_length=30),
        ),
        migrations.AddField(
            model_name='mission',
            name='completion_rule',
            field=models.CharField(choices=[('interviews_learning', 'Entrevistas e aprendizado'), ('primary_submission', 'Entregavel principal')], default='interviews_learning', max_length=30),
        ),
        migrations.AddField(
            model_name='mission',
            name='definition_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='origin',
            field=models.CharField(choices=[('catalog', 'Catalogo'), ('dynamic', 'Dinamica')], default='catalog', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='prerequisite_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='requirement_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mission',
            name='step_blueprint',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='missionevidence',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='missionevidence',
            name='submission_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='missionevidence',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='missionevidence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('interview_recorded', 'Entrevista registrada'), ('evidence_recorded', 'Evidencia registrada'), ('learning_recorded', 'Aprendizado registrado'), ('mission_completed', 'Missao concluida'), ('journey_step_completed', 'Etapa concluida'), ('decision_recorded', 'Decisao registrada'), ('goal_completed', 'Meta concluida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='missionevidence',
            name='interviewee_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='missionevidence',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='missionevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_key__gt', '')), fields=('mission', 'submission_key'), name='unique_submission_key_per_mission'),
        ),
    ]
