# Generated by Django 5.2.16 on 2026-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0009_startup_is_test_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('interview_recorded', 'Entrevista registrada'), ('evidence_recorded', 'Evidência registrada'), ('learning_recorded', 'Aprendizado registrado'), ('mission_completed', 'Missão concluída'), ('journey_step_completed', 'Etapa concluída'), ('decision_recorded', 'Decisão registrada'), ('goal_completed', 'Meta concluída')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='key',
            field=models.CharField(choices=[('problem', 'Definição do problema'), ('audience', 'Público-alvo'), ('value', 'Proposta de valor'), ('differentiators', 'Diferenciais'), ('validation', 'Validação inicial'), ('business_model', 'Modelo de negócio'), ('mvp', 'Planejamento do MVP'), ('goals', 'Metas iniciais')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journeystep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('current', 'Etapa atual'), ('done', 'Concluída')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='learning',
            name='confidence',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='action_type',
            field=models.CharField(choices=[('interviews', 'Entrevistas'), ('problem_refinement', 'Refinamento do problema'), ('audience_validation', 'Validação do público'), ('value_proposition', 'Proposta de valor'), ('alternatives_map', 'Mapa de alternativas')], default='interviews', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='completion_rule',
            field=models.CharField(choices=[('interviews_learning', 'Entrevistas e aprendizado'), ('primary_submission', 'Entregável principal')], default='interviews_learning', max_length=30),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('main', 'Missão principal'), ('weekly', 'Missão semanal'), ('quick', 'Tarefa rápida'), ('experiment', 'Experimento'), ('learning', 'Aprendizado'), ('management', 'Gestão recorrente')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='origin',
            field=models.CharField(choices=[('catalog', 'Catálogo'), ('dynamic', 'Dinâmica')], default='catalog', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('locked', 'Bloqueada'), ('available', 'Disponível'), ('in_progress', 'Em andamento'), ('completed', 'Concluída')], default='locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionevidence',
            name='evidence_type',
            field=models.CharField(choices=[('interview', 'Entrevista'), ('experiment', 'Resultado de experimento'), ('document', 'Documento'), ('metric', 'Métrica'), ('other', 'Outra evidência')], default='interview', max_length=20),
        ),
        migrations.AlterField(
            model_name='startup',
            name='current_stage',
            field=models.CharField(choices=[('problem', 'Definição do problema'), ('audience', 'Público-alvo'), ('value', 'Proposta de valor'), ('differentiators', 'Diferenciais'), ('validation', 'Validação inicial'), ('business_model', 'Modelo de negócio'), ('mvp', 'Planejamento do MVP'), ('goals', 'Metas iniciais')], default='problem', max_length=20),
        ),
    ]
